::  Tests for /lib/gviz-web.
::
/-  gviz
/+  *test, web=gviz-web
|%
::
++  test-web-page
  =/  html  page:web
  ;:  weld
    (expect !>(?=(^ (find "Graph Viz" (trip html)))))
    (expect !>(?=(^ (find "/apps/graph-viz/app.js" (trip html)))))
    (expect !>(?=(^ (find "/apps/graph-viz/ace/ace.js" (trip html)))))
    (expect !>(?=(^ (find "/apps/graph-viz/ace/graph-viz-config.js" (trip html)))))
    (expect !>(?=(^ (find "/apps/graph-viz/ace/mode-dot.js" (trip html)))))
    (expect !>(?=(^ (find "/apps/graph-viz/ace/theme-github.js" (trip html)))))
    (expect !>(?=(^ (find "/apps/graph-viz/ace/ext-beautify.js" (trip html)))))
    (expect !>(?=(~ (find "<script src=\"http" (trip html)))))
    (expect !>(?=(^ (find "id=\"workspace\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"splitter\"" (trip html)))))
    (expect !>(?=(~ (find "id=\"download\"" (trip html)))))
    (expect !>(?=(~ (find "id=\"download-dot\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"browse-dot\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"load-dot\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"save-dot\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"browse-svg\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"load-svg\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"save-svg\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"toggle-svg-source\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"copy-svg\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"fullscreen-svg\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"svg-source\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"explorer-pane\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"explorer-tabs\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"dot-files-tab\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"svg-files-tab\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"dot-files-tree\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"svg-files-tree\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"file-context-menu\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"file-context-open\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"file-context-delete\"" (trip html)))))
    (expect !>(?=(~ (find "id=\"file-browser-modal\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"clay-error-modal\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"clay-error-message\"" (trip html)))))
    (expect !>(?=(~ (find "id=\"share\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"auto-render\"" (trip html)))))
    (expect !>(?=(^ (find "source-auto-render" (trip html)))))
    (expect !>(?=(^ (find "id=\"theme\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"help\"" (trip html)))))
    (expect !>(?=(^ (find "role=\"dialog\"" (trip html)))))
    (expect !>(?=(^ (find "aria-modal=\"true\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"fallback-help-content\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"docs-help-content\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"docs-help-nav\"" (trip html)))))
    (expect !>(?=(~ (find "id=\"docs-help-frame\"" (trip html)))))
    (expect !>(?=(^ (find "LLM skill files" (trip html)))))
    (expect !>(?=(^ (find "gviz-dot-syntax" (trip html)))))
    (expect !>(?=(^ (find "gviz-gall-api" (trip html)))))
    (expect !>(?=(^ (find "gviz-patterns" (trip html)))))
    (expect !>(?=(^ (find "DOT Syntax LLM Skill" (trip html)))))
    (expect !>(?=(^ (find "Gall API LLM Skill" (trip html)))))
    (expect !>(?=(^ (find "Common Patterns LLM Skill" (trip html)))))
    (expect !>(?=(^ (find "id=\"zoom-out\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"zoom-in\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"fullscreen-zoom-out\"" (trip html)))))
    (expect !>(?=(^ (find "id=\"fullscreen-zoom-in\"" (trip html)))))
    (expect !>(?=(^ (find "data-state=\"empty\"" (trip html)))))
  ==
::
++  test-theme-switcher
  =/  html  (trip page:web)
  =/  style  (trip css:web)
  =/  script  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "value=\"system\"" html))))
    (expect !>(?=(^ (find "value=\"light\"" html))))
    (expect !>(?=(^ (find "value=\"dark\"" html))))
    (expect !>(?=(^ (find "preferences?.theme" html))))
    (expect !>(?=(^ (find "dataset.effectiveTheme" html))))
    (expect !>(?=(^ (find "prefers-color-scheme: dark" html))))
    (expect !>(?=(^ (find "data-effective-theme='dark'" style))))
    (expect !>(?=(^ (find "color-scheme: dark" style))))
    (expect !>(?=(^ (find "--surface-alt" style))))
    (expect !>(?=(^ (find "var(--preview-background)" style))))
    (expect !>(?=(^ (find "var(--inspector-background)" style))))
    (expect !>(?=(^ (find ".preview svg" style))))
    (expect !>(?=(^ (find "filter: invert(1) hue-rotate(180deg)" style))))
    (expect !>(?=(~ (find "  background: #ffffff" style))))
    (expect !>(?=(~ (find "  background: #fafafa" style))))
    (expect !>(?=(~ (find "  background: #f4f4f5" style))))
    (expect !>(?=(^ (find "function applyTheme" script))))
    (expect !>(?=(^ (find "function systemThemeChanged" script))))
    (expect !>(?=(^ (find "themeMedia.addEventListener" script))))
    (expect !>(?=(^ (find "theme: validTheme(preferences.theme)" script))))
    (expect !>(?=(^ (find "theme: theme.value" script))))
  ==
::
++  test-docs-help
  =/  html  (trip page:web)
  =/  style  (trip css:web)
  =/  script  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "/docs/d/graph-viz/usr/users-guide" html))))
    (expect !>(?=(^ (find "Users Guide" html))))
    (expect !>(?=(^ (find "/docs/d/graph-viz/reference" html))))
    (expect !>(?=(^ (find "/docs/d/graph-viz/graph-noun" html))))
    (expect !>(?=(^ (find "/docs/d/graph-viz/release-notes" html))))
    (expect !>(?=(~ (find "src=\"/docs/d/graph-viz/" html))))
    (expect !>(?=(^ (find "<details class=\"docs-help-group\">" html))))
    (expect !>(?=(^ (find ".docs-help-content" style))))
    (expect !>(?=(^ (find ".docs-explorer-frame" style))))
    (expect !>(?=(^ (find "fetch('/docs'" script))))
    (expect !>(?=(^ (find "credentials: 'same-origin'" script))))
    (expect !>(?=(^ (find "cache: 'no-store'" script))))
    (expect !>(?=(^ (find "responseUrl.origin" script))))
    (expect !>(?=(^ (find "responseUrl.pathname === '/docs'" script))))
    (expect !>(?=(^ (find "contentType.includes('text/html')" script))))
    (expect !>(?=(^ (find "function setHelpVariant" script))))
    (expect !>(?=(^ (find "function refreshHelpVariant" script))))
    (expect !>(?=(^ (find "function docsTabLabel" script))))
    (expect !>(?=(~ (find "function createHelpTab" script))))
    (expect !>(?=(~ (find "function closeHelpTab" script))))
    (expect !>(?=(~ (find "svgControl.after(wrapper)" script))))
    (expect !>(?=(^ (find "function setHelpOpen" script))))
    (expect !>(?=(^ (find "helpPanel.hidden = !open" script))))
    (expect !>(?=(^ (find "function openDocsTab" script))))
    (expect !>(?=(^ (find "function closeDocsTab" script))))
    (expect !>(?=(^ (find "function explorerTabKeydown" script))))
    (expect !>(?=(^ (find "frame.src" script))))
    (expect !>(?=(^ (find "fallbackHelpContent.hidden" script))))
    (expect !>(?=(^ (find "function disableDocsExplorer" script))))
  ==
::
++  test-responsive-shell
  =/  script  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "@media (max-width: 760px)" (trip css:web)))))
    (expect !>(?=(^ (find "pointerdown" script))))
    (expect !>(?=(^ (find "disconnected" script))))
    (expect !>(?=(^ (find "bounds.width - explorerDividerWidth" script))))
    (expect !>(?=(~ (find "Math.min(640" script))))
  ==
::
++  test-live-rendering
  =/  js  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "setTimeout(render, renderDelay)" js))))
    (expect !>(?=(^ (find "uid !== latestRequestUid" js))))
    (expect !>(?=(^ (find "x-graph-viz-request" js))))
    (expect !>(?=(^ (find "problem.line" js))))
    (expect !>(?=(^ (find "problem.column" js))))
    (expect !>(?=(^ (find "Unsupported feature" js))))
    (expect !>(?=(^ (find "Layout error" js))))
    (expect !>(?=(^ (find "hasPreview ? 'ready' : 'empty'" js))))
  ==
::
++  test-safe-svg-controls
  =/  js  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "new DOMParser()" js))))
    (expect !>(?=(^ (find "image/svg+xml" js))))
    (expect !>(?=(^ (find "document.importNode" js))))
    (expect !>(?=(^ (find "unsafe SVG response" js))))
    (expect !>(?=(^ (find ":scope > title" js))))
    (expect !>(?=(^ (find "fitToWindow" js))))
    (expect !>(?=(^ (find "zoomAtCenter" js))))
    (expect !>(?=(^ (find "addEventListener('wheel'" js))))
    (expect !>(?=(^ (find "addEventListener('pointermove'" js))))
    (expect !>(?=(^ (find "replaceChildren(svg)" js))))
  ==
::
++  test-editor-usability
  =/  html  (trip page:web)
  =/  js  (trip javascript:web)
  ;:  weld
    (expect !>(?=(~ (find "id=\"line-numbers\"" html))))
    (expect !>(?=(~ (find "<textarea" html))))
    (expect !>(?=(^ (find "id=\"dot\"" html))))
    (expect !>(?=(^ (find "id=\"editor-load-error\"" html))))
    (expect !>(?=(^ (find "Select template…" html))))
    (expect !>(?=(^ (find "value=\"\" disabled=\"\" hidden=\"\"" html))))
    (expect !>(?=(~ (find ">Templates<" html))))
    (expect !>(?=(^ (find "value=\"flowchart\"" html))))
    (expect !>(?=(^ (find "value=\"strict-digraph\"" html))))
    (expect !>(?=(^ (find "value=\"state-machine\"" html))))
    (expect !>(?=(^ (find "value=\"dependencies\"" html))))
    (expect !>(?=(^ (find "value=\"clusters\"" html))))
    (expect !>(?=(^ (find "strict digraph unique_edges" js))))
    (expect !>(?=(^ (find "last wins" js))))
    (expect !>(?=(^ (find "createAceEditorAdapter" js))))
    (expect !>(?=(^ (find "window.ace.edit" js))))
    (expect !>(?=(^ (find "session.setMode" js))))
    (expect !>(?=(^ (find "session.setUseWorker" js))))
    (expect !>(?=(^ (find "showPrintMargin: false" js))))
    (expect !>(?=(^ (find "tabSize: 2" js))))
    (expect !>(?=(^ (find "useSoftTabs: true" js))))
    (expect !>(?=(^ (find "wrap: true" js))))
    (expect !>(?=(^ (find "addCommands(beautify.commands)" js))))
    (expect !>(?=(^ (find "bindKey('Ctrl-T', 'transposeletters')" js))))
    (expect !>(?=(~ (find "createTextareaEditorAdapter" js))))
    (expect !>(?=(~ (find "handleTab" js))))
    (expect !>(?=(^ (find "handleShortcut" js))))
    (expect !>(?=(^ (find "loadCurrentSvg" js))))
  ==
::
++  test-persistence-export
  =/  js  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "graph-viz.session.v1" js))))
    (expect !>(?=(^ (find "localStorage.setItem" js))))
    (expect !>(?=(^ (find "localStorage.getItem" js))))
    (expect !>(?=(^ (find "preferences:" js))))
    (expect !>(?=(^ (find "autoRender: autoRender.checked" js))))
    (expect !>(?=(^ (find "theme: theme.value" js))))
    (expect !>(?=(^ (find "paneWidth: currentPaneWidth()" js))))
    (expect !>(?=(^ (find "explorerWidth: currentExplorerWidth()" js))))
    (expect !>(?=(^ (find "explorerView," js))))
    (expect !>(?=(^ (find "docsTabs," js))))
    (expect !>(?=(^ (find "nextDocs," js))))
    (expect !>(?=(^ (find "loadCurrentDot" js))))
    (expect !>(?=(^ (find "saveCurrentDot" js))))
    (expect !>(?=(^ (find "saveCurrentSvg" js))))
    (expect !>(?=(^ (find "setSvgSourceVisible" js))))
    (expect !>(?=(^ (find "toggleSvgView" js))))
    (expect !>(?=(^ (find "copySvgSource" js))))
    (expect !>(?=(^ (find "navigator.clipboard.writeText" js))))
    (expect !>(?=(^ (find "toggleSvgFullscreen" js))))
    (expect !>(?=(^ (find "requestFullscreen" js))))
    (expect !>(?=(^ (find "exitFullscreen" js))))
    (expect !>(?=(^ (find "autoRender.checked = false" js))))
    (expect !>(?=(^ (find "showClayError(cause)" js))))
    (expect !>(?=(^ (find "function openFileContext" js))))
    (expect !>(?=(^ (find "function deleteContextFile" js))))
    (expect !>(?=(^ (find "addEventListener('contextmenu'" js))))
    (expect !>(?=(^ (find "clayFileRequest(kind, 'delete'" js))))
    (expect !>(?=(^ (find "x-graph-viz-path" js))))
    (expect !>(?=(^ (find "x-graph-viz-overwrite" js))))
    (expect !>(?=(^ (find "response.status === 409" js))))
    (expect !>(?=(^ (find "already exists. Overwrite it?" js))))
    (expect !>(?=(~ (find "copyShareUrl" js))))
    (expect !>(?=(^ (find "encodeSource" js))))
    (expect !>(?=(^ (find "decodeSource" js))))
    (expect !>(?=(^ (find "maxSharedSourceBytes" js))))
    (expect !>(?=(^ (find "sourceFromUrl" js))))
  ==
::
++  test-visual-selection
  =/  html  (trip page:web)
  =/  js  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "id=\"inspector\"" html))))
    (expect !>(?=(^ (find "id=\"selection-kind\"" html))))
    (expect !>(?=(^ (find "id=\"selection-id\"" html))))
    (expect !>(?=(^ (find "id=\"clear-selection\"" html))))
    (expect !>(?=(^ (find ".is-selected" (trip css:web)))))
    (expect !>(?=(^ (find "dotStatements" js))))
    (expect !>(?=(^ (find "sourceRangeFor" js))))
    (expect !>(?=(^ (find "selectSourceStatement" js))))
    (expect !>(?=(^ (find "selectVisualElement" js))))
    (expect !>(?=(^ (find "aria-current" js))))
    (expect !>(?=(^ (find "tabindex" js))))
  ==
::
++  test-visual-editing
  =/  html  (trip page:web)
  =/  js  (trip javascript:web)
  ;:  weld
    (expect !>(?=(^ (find "id=\"new-node-name\"" html))))
    (expect !>(?=(^ (find "id=\"new-node-category\"" html))))
    (expect !>(?=(^ (find "id=\"new-node-shape\"" html))))
    (expect !>(?=(^ (find "id=\"add-node\"" html))))
    (expect !>(?=(^ (find "id=\"draw-edge\"" html))))
    (expect !>(?=(^ (find "id=\"attribute-form\"" html))))
    (expect !>(?=(^ (find "id=\"edge-controls\"" html))))
    (expect !>(?=(^ (find "id=\"attr-arrowhead\"" html))))
    (expect !>(?=(^ (find "id=\"attr-arrowtail\"" html))))
    (expect !>(?=(^ (find "id=\"attr-arrowsize\"" html))))
    (expect !>(?=(^ (find "id=\"attr-dir\"" html))))
    (expect !>(?=(^ (find "id=\"attr-minlen\"" html))))
    (expect !>(?=(^ (find "id=\"attr-weight\"" html))))
    (expect !>(?=(^ (find "id=\"attr-penwidth\"" html))))
    (expect !>(?=(^ (find "id=\"attr-fontname\"" html))))
    (expect !>(?=(^ (find "id=\"attr-fontsize\"" html))))
    (expect !>(?=(^ (find "id=\"attr-fontcolor\"" html))))
    (expect !>(?=(^ (find "id=\"attr-change-all\"" html))))
    (expect !>(?=(^ (find "id=\"attr-use-default\"" html))))
    (expect !>(?=(^ (find "#shape-control[hidden]" (trip css:web)))))
    (expect !>(?=(^ (find "id=\"delete-selection\"" html))))
    (expect !>(?=(^ (find "addVisualNode" js))))
    (expect !>(?=(^ (find "nodeShapeCategories" js))))
    (expect !>(?=(^ (find "populateNewNodeShapes" js))))
    (expect !>(?=(^ (find "populateAttributeShapes" js))))
    (expect !>(?=(^ (find "drawSelectedEdge" js))))
    (expect !>(?=(^ (find "deleteSelectedItem" js))))
    (expect !>(?=(^ (find "applySelectedAttributes" js))))
    (expect !>(?=(^ (find "changeAllAttributes" js))))
    (expect !>(?=(^ (find "addAttributeDefault" js))))
    (expect !>(?=(^ (find "readStatementAttributes" js))))
    (expect !>(?=(^ (find "insertRootStatement" js))))
    (expect !>(?=(^ (find "splitEdgeStatement" js))))
  ==
::
++  test-web-error-json
  =/  txt  (error-text:web [%parse 2 7 'bad "quote"\\line\0anext'])
  ;:  weld
    (expect !>(?=(^ (find "\"kind\":\"parse\"" (trip txt)))))
    (expect !>(?=(^ (find "\"line\":2" (trip txt)))))
    (expect !>(?=(^ (find "\"column\":7" (trip txt)))))
    (expect !>(?=(^ (find "bad \\\"quote\\\"\\\\line\\nnext" (trip txt)))))
  ==
--
